create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  message text not null check (char_length(message) between 5 and 1200),
  email text check (email is null or char_length(email) <= 254),
  page_url text check (page_url is null or char_length(page_url) <= 500),
  created_at timestamptz not null default now()
);

alter table public.feedback enable row level security;

create policy "Anyone can submit feedback"
on public.feedback
for insert
to anon, authenticated
with check (
  char_length(message) between 5 and 1200
  and (email is null or char_length(email) <= 254)
);

-- There is intentionally no public SELECT policy. Only project administrators
-- can read feedback in the Supabase dashboard.
